export const entityPriorities: Record<string, number> = {
  payment_methods: 10,
  menu_category: 10,
  coffees: 10,
  suppliers: 10,
  customers: 10,
  services: 10,
  cash_register_stock_items: 10,
  raw_materials: 20,
  recipes: 20,
  menu_items: 20,
  stock_products: 20,
  installments: 20,
  cost_products: 20,
  fixed_costs: 20,
  recipe_ingredients: 30,
  stock_menu_item_map: 30,
  cash_register_stock_item_menu_map: 30,
  orders: 40,
  cash_register_shifts: 40,
  report_expenses: 40,
  service_payments: 40,
  installment_payments: 40,
  customer_account_payments: 40,
  order_items: 50,
  stock_movements: 50,
  price_history: 50,
  calibrations: 50,
};

export const replicatedTables = Object.keys(entityPriorities);
